algoritmo "Sala do Data Center"

var
largura: real
comprimento: real


inicio

escreval("Coletando informações para preparação do datacenter")
escreval("Informe a largura da sala")
leia(largura)
escreval("Informe o comprimento da sala")
leia(comprimento)
escreval("A área da sala é " ,largura*comprimento,"")
escreval("O perimetro de sala é " ,comprimento*2+largura*2,"")



fimalgoritmo